# Generated by Django 3.2.5 on 2021-07-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('colors', models.CharField(max_length=200)),
                ('view_color', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
