# Generated by Django 3.2.5 on 2021-07-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(default='white', max_length=200),
        ),
    ]
