# Generated by Django 3.2.5 on 2021-07-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view_color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
