# Generated by Django 3.2.5 on 2021-07-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210711_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(default='white', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
