# Generated by Django 3.2.5 on 2021-07-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210711_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mockupImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
