# Generated by Django 3.2.5 on 2021-07-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_product_mockupimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mockupData',
            field=models.TextField(null=True),
        ),
    ]
