# Generated by Django 3.2.5 on 2021-07-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_product_mockupdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mockupImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
