# Generated by Django 3.2.5 on 2021-07-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_product_mockupimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mockupImg',
        ),
        migrations.AlterField(
            model_name='product',
            name='mockupData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
