# Generated by Django 3.2.5 on 2021-07-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_product_mockupdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mockupImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
