# Generated by Django 3.2.5 on 2021-07-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_product_mockupimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mockupData',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mockupImg',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
