# Generated by Django 3.2.5 on 2021-07-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210714_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mockupData',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='mockupImg',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
