# Generated by Django 3.2.5 on 2021-07-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_product_mockupimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mockupData',
            field=models.TextField(blank=True),
        ),
    ]
