# Generated by Django 3.2.5 on 2021-07-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_product_mockupdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mockupData',
        ),
    ]
