# Generated by Django 3.2.5 on 2021-07-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_product_mockupdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mockupData',
            field=models.TextField(blank=True),
        ),
    ]
