# Generated by Django 3.2.5 on 2021-07-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20210720_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mockupDataPink',
            field=models.TextField(blank=True),
        ),
    ]
